version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: finance-app-postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: finance-app
        ports:
            - '5432:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
volumes:
    postgres:
